import { NgModule } from '@angular/core';
import {
  IonInput,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonGrid,
  IonCol,
  IonRow,
  IonButton,
  IonIcon,
  IonItem,
  IonList,
  IonLabel,
  IonImg,
  IonSegment,
  IonSegmentButton,
} from '@ionic/angular/standalone';

@NgModule({
  declarations: [],
  imports: [
    IonCard,
    IonInput,
    IonImg,
    IonList,
    IonItem,
    IonIcon,
    IonButton,
    IonRow,
    IonLabel,
    IonCol,
    IonGrid,
    IonImg,
    IonCardContent,
    IonCardSubtitle,
    IonCardTitle,
    IonCardHeader,
    IonSegment,
    IonSegmentButton,
  ],
  exports: [
    IonCard,
    IonInput,
    IonImg,
    IonList,
    IonItem,
    IonIcon,
    IonButton,
    IonLabel,
    IonImg,
    IonRow,
    IonCol,
    IonGrid,
    IonCardContent,
    IonCardSubtitle,
    IonCardTitle,
    IonCardHeader,
    IonSegment,
    IonSegmentButton,
  ],
})
export class UiEssentials {}
