import { NgModule } from '@angular/core';
import {
  IonAvatar,
  IonInput,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonGrid,
  IonChip,
  IonCol,
  IonRow,
  IonIcon,
  IonItem,
  IonList,
  IonListHeader,
  IonLabel,
  IonImg,
  IonModal,
  IonNote,
  IonSegment,
  IonSegmentButton,
} from '@ionic/angular/standalone';

@NgModule({
  declarations: [],
  imports: [
    IonAvatar,
    IonCard,
    IonChip,
    IonInput,
    IonImg,
    IonList,
    IonItem,
    IonIcon,
    IonRow,
    IonListHeader,
    IonLabel,
    IonCol,
    IonGrid,
    IonImg,
    IonCardContent,
    IonCardSubtitle,
    IonCardTitle,
    IonCardHeader,
    IonModal,
    IonSegment,
    IonNote,
    IonSegmentButton,
  ],
  exports: [
    IonAvatar,
    IonCard,
    IonChip,
    IonInput,
    IonImg,
    IonList,
    IonListHeader,
    IonItem,
    IonIcon,
    IonLabel,
    IonImg,
    IonRow,
    IonCol,
    IonGrid,
    IonCardContent,
    IonCardSubtitle,
    IonCardTitle,
    IonCardHeader,
    IonNote,
    IonModal,
    IonSegment,
    IonSegmentButton,
  ],
})
export class UiEssentials {}
